### ISSUE TITLE
Hey, this is getting 502 bad gateeway while deploying on netlify, how'd you fix it in your app?

### ISSUE THREAD

**Issue by 0xrpj** [depatchedmode/simplest-frame#3]

**Comment by 0xrpj** [comment]
<img width="957" alt="image" src="https://github.com/depatchedmode/simplest-frame/assets/56220537/ba9bc4bd-4f72-4cc6-96af-bddeb6af6572">

**Comment by 0xrpj** [comment]
I was working on macOS.

Fixed with this command:
npm install --platform=linux --arch=x64 sharp

**Comment by depatchedmode** [comment]
Thanks @0xrpj! There might be a need for us to remove the `package-lock.json` as I think that npm install command will fix the deployed environment for some folks, but end up breaking local.

Either way, I'll link to this thread from the README for now. And I'm gonna re-open the issue so other people can add information as we learn where it stands up and falls down.

**Comment by GudCode** [comment]
Any fix available yet? Thanks!

**Comment by depatchedmode** [comment]
@GudCode You're experiencing this issue? It should be fixed now with netlify deploys since locking to a lower version of Satori and removing the package-lock.json 

If you ran `npm update` that could be a reason you're experiencing this. Try deleting the `node_modules` directory and `package-lock.json` locally and then running `npm install` again and see if it fixes stuff.

**Comment by GudCode** [comment]
Yes, no luck. When I test it in https://warpcast.com/~/developers/frames by clicking the frame's button. I get:
<netlifyurl>?frame=poster
postFakeCastFrameAction 400 - Failed to post fake frame action: Failed to post to frame. Error: Request failed with status code 502

**Comment by GudCode** [comment]
@depatchedmode Any ideas why this is occurring? Thanks!

**Comment by depatchedmode** [comment]
@GudCode Bit stumped, honestly. This might be the moment where we need a real dev.

Let me find time to look at this along some other upgrades this week. Can you share a link to the deployed frame so that I can test against the error?

**Comment by depatchedmode** [comment]
@beeboopx Couple of questions and I should be able to help:
1. Which version of `simplest-frame` are you on? I fixed some things last night for v0.11.1
2. What operating system are you developing from locally? There will be differences in the sharp build used locally, versus the one used on Netlify. Hoping to find a way for this to be accounted for by default but need to do more testing.
3. Do you have any logs you can share of the error? Might help to debug your specific case.

**Comment by i001962** [comment]
I've also been getting a sharp error.
Deploys fine but borks when run
using version 12.0 
git clone
npm i
netlify deploy --prod

Any ideas how to get around this?

May 11, 02:38:22 PM: 71f3dfd9 Duration: 1652.36 ms	Memory Usage: 58 MB	May 11, 02:38:23 PM: 2024-05-11T21:38:23.280Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"\nSomething went wrong installing the \"sharp\" module\n\nCannot find module '../build/Release/sharp-linux-x64.node'\nRequire stack:\n- /var/task/node_modules/sharp/lib/sharp.js\n- /var/task/node_modules/sharp/lib/constructor.js\n- /var/task/node_modules/sharp/lib/index.js\n\nPossible solutions:\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install","stack":["Error: ","Something went wrong installing the \"sharp\" module","","Cannot find module '../build/Release/sharp-linux-x64.node'","Require stack:","- /var/task/node_modules/sharp/lib/sharp.js","- /var/task/node_modules/sharp/lib/constructor.js","- /var/task/node_modules/sharp/lib/index.js","","Possible solutions:","- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"","- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"","- Consult the installation documentation: https://sharp.pixelplumbing.com/install","    at Object.<anonymous> (/var/task/node_modules/sharp/lib/sharp.js:37:9)","    at Module._compile (node:internal/modules/cjs/loader:1364:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)","    at Module.load (node:internal/modules/cjs/loader:1203:32)","    at Module._load (node:internal/modules/cjs/loader:1019:12)","    at Module.require (node:internal/modules/cjs/loader:1231:19)","    at require (node:internal/modules/helpers:177:18)","    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:11:1)","    at Module._compile (node:internal/modules/cjs/loader:1364:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)"]}May
